-initial work on vampire

diff --git a/Docker/Dockerfile-vampire b/Docker/Dockerfile-vampire
--- a/Docker/Dockerfile-vampire
+++ b/Docker/Dockerfile-vampire
@@ -28,7 +28,11 @@ COPY inference/eprover.p /vampire/
 RUN pip install -r requirements.txt
 
 # Run the sysctl command to modify kernel settings (this works only in privileged mode)
-# RUN sysctl -w kernel.perf_event_paranoid=-1 || echo "Ignoring sysctl failure, needs privileged mode."
+RUN sudo sysctl -w kernel.perf_event_paranoid=-1 || echo "Ignoring sysctl failure, needs privileged mode."
 
 # Set the command to run the Python script
-CMD ["python", "run_vampire.py"]
+CMD ["bin/vampire", "eprover.p"]
+#CMD ["python", "run_vampire.py"]
+CMD ["uvicorn", "run_vampire:app", "--host", "0.0.0.0", "--port", "8082", "--reload"]
+#CMD ["fastapi", "run", "run_vampire.py", "--port", "8082"]
+#uvicorn main:app --host 0.0.0.0 --port 80
